version: "3.8"

services:
    db:
        image: library/postgres:12.4-alpine
        environment:
            POSTGRES_DB: archive
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./db:/var/lib/postgresql

    backend:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "9000:8000"
        depends_on:
            - db
