# Generated by Django 3.1.2 on 2020-10-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="file", name="url", field=models.URLField(null=True),
        ),
    ]
